### ISSUE TITLE
Replace pydot with graphviz

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/decaylanguage#105]
The package [pydot](https://github.com/pydot/pydot) is no longer maintained, as obvious from the time (Dec. 2018) of the last commit and the increasing number of open issues. We should switch to [graphviz](https://github.com/xflr6/graphviz) in the near future.

**Comment by Bhanu-mbvg** [comment]
I would like to work on this

**Comment by eduardo-rodrigues** [comment]
Great. Looking forward to it.

For you to get started: when forking the repository you will see that `pydot` is used in the `decay/viewer.py`. The idea is to replace all occurrences and related doc with the `graphviz` package, which is maintained. You can use for example the demo notebook with `pydot` or `graphviz` to compare your work and make sure all is OK. Let me know how you get along. Free free to post questions. Thanks.

**Comment by Bhanu-mbvg** [comment]
Hey sure I'll get started thank you for the head's up. Will reach out to you if I face any issues

**Comment by Bhanu-mbvg** [comment]
Hey @eduardo-rodrigues , I'm having little doubts with 'pydot.Dot' and setting default node and edge migrations hope you can help.  

![image](https://user-images.githubusercontent.com/44861163/102641406-09267000-4182-11eb-9747-3a1f21460e70.png)

**Comment by eduardo-rodrigues** [comment]
(I will be slow from now on since starting holidays.)

This bit of code is simply to make sure that a nice set of defaults are used, well, by default, but that the user can still have the flexibility to change some of the settings such as colours. The one thing the user is not allowed to do is change the graph type, which makes sense. What is the trouble? I assume that graphviz is able to deal with defaults for the underlying DOT language graph.

**Comment by eduardo-rodrigues** [comment]
You should look at the defaults I set via the `_get_XX_defaults` methods ...

Does that help or you're having trouble with something else?

**Comment by eduardo-rodrigues** [comment]
BTW, feel free to make a first stab at the work specifying it as draft/WIP and it's then easy to review and iterate.
