### ISSUE TITLE
Remove constraint on Lark version and update to most recent ones

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/decaylanguage#130]
See discussion at https://github.com/scikit-hep/decaylanguage/pull/129#discussion_r601668378.

**Comment by eduardo-rodrigues** [comment]
Since you @simonthor are working with this package and developing - if you ever have a bit of time and interest in parsers then I would very much appreciate help on this task! Let me know.

**Comment by simonthor** [comment]
Apologies for the delayed response. I have not worked much with parsers before but I will take a look at Lark the next week to see if it is something that interests me. However, I can unfortunately cannot guarantee that I will be able to help on this issue.

**Comment by eduardo-rodrigues** [comment]
> Apologies for the delayed response. I have not worked much with parsers before but I will take a look at Lark the next week to see if it is something that interests me. However, I can unfortunately cannot guarantee that I will be able to help on this issue.

There's no worry at all, understood. *Any* help is good help. Thank you.
