### ISSUE TITLE
Update importlib.resources usage

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/decaylanguage#138]
We should use the newer interface (3.8+ or 3.9+ with backport), it's much simpler to use. It's also very unevenly used in the current package; hopefully we can use it consistently once we use the new API.

**Comment by eduardo-rodrigues** [comment]
Can you be more specific @henryiii? What are you suggesting to adapt to in
```
if sys.version_info < (3, 7):
    from importlib_resources import open_text
else:
    from importlib.resources import open_text
```

**Comment by eduardo-rodrigues** [comment]
Hey @henryiii, if you could clarify what you mean here that would be great, so that we try and get this task closed asap. Advance thanks.

**Comment by eduardo-rodrigues** [comment]
Closing since I believe there is nothing to be done here at this stage. Feel free to re-open if you have a suggestion that I missed.

**Comment by henryiii** [comment]
Sorry, what I meant was there's a new unified interface that was introduced in 3.8 or 3.9 that's cleaner and simpler than `open_text`. In the new form, it's

```python
if sys.version_info < (3, 9):
    from importlib_resources import files
else:
    from importlib.resources import files
```

`files` behaves a lot like a `pathlib.Path`, and you can just use normal methods on it. If you want to make it provide a "real" path even inside a zip file, you can directly place it in a context manager.

**Comment by henryiii** [comment]
An example:

```python
import data

# before
with data.open_text(data, "DECAY_LHCB.DEC") as f:
        txt = f.read()

# after

with data.files(data).joinpath("DECAY_LHCB.DEC").open() as f:
    txt = f.read()

# or
txt = data.files(data).joinpath("DECAY_LHCB.DEC").read_text()
```

We might even be able to wrap `data.files(data)` into something that can be used directly.

**Comment by eduardo-rodrigues** [comment]
I see. Thanks for this feature that I was not aware of. Shall we reopen and try and adapt, then? Fine by me also if you do it. Otherwise I keep the task open for asap ...

**Comment by henryiii** [comment]
I'm going to try to do this later today.
