### ISSUE TITLE
Either or type decay chains

### ISSUE THREAD

**Issue by psadangi95** [scikit-hep/decaylanguage#170]
Hi @eduardo-rodrigues  @henryiii 

I am not sure if, either or type chains are possible to write in decay language. I can give an example. Suppose a meson decays to tau+ and tau-. And one of the taus should go to muon and another one should go to 3 pions and charge conjugation decays will be according to the charges, but they shouldn't repeat, (say tau+ to mu+ and tau- to mu- is not allowed). Is it possible here? If so please help!

**Comment by eduardo-rodrigues** [comment]
Hello @psadangi95. Thank you for the interest in the package. There are two "types" of decay chains one can define: those defined via .dec decay files as for EvtGen, and decay chains defined via the classes such as "DecayChain" and friends. You seem to be interested in the former from your description. The task seems very easy if I understand it correctly. You should look at examples of .dec files as in https://github.com/scikit-hep/decaylanguage/tree/master/src/decaylanguage/data and https://github.com/scikit-hep/decaylanguage/tree/master/tests/data. I'm having some days off but we can finalise on this soon. Hopefully these pointers will get you started/done. Let us know.

**Comment by psadangi95** [comment]
> Hello @psadangi95. Thank you for the interest in the package. There are two "types" of decay chains one can define: those defined via .dec decay files as for EvtGen, and decay chains defined via the classes such as "DecayChain" and friends. You seem to be interested in the former from your description. The task seems very easy if I understand it correctly. You should look at examples of .dec files as in https://github.com/scikit-hep/decaylanguage/tree/master/src/decaylanguage/data and https://github.com/scikit-hep/decaylanguage/tree/master/tests/data. I'm having some days off but we can finalise on this soon. Hopefully these pointers will get you started/done. Let us know.

Hi @eduardo-rodrigues 
I already looked into those examples, but what i want is not mentioned in any of the examples. Even i tried, but there are some cases where i get both taus to have same final states, if i define separately for tau+ and tau- then it will not be correct also as the alternate decays can't be possible. (say, if i write the decay files as, tau+ ->mu+, tau- ->3 pi .. now how tau- will decay to mu-  and tau + will decay to 3 pi ? If you think somehow it is possible defining the decays individually it would be really great if you comment. Thanks a lot.

**Comment by eduardo-rodrigues** [comment]
Posting here your reply, which I got via email but was not put on GitLab:

> Hi @eduardo-rodrigues
I already looked into those examples, but what i want is not mentioned in any of the examples. Even i tried, but there are some cases where i get both taus to have same final states, if i define separately for tau+ and tau- then it will not be correct also as the alternate decays can't be possible. (say, if i write the decay files as, tau+ ->mu+, tau- ->3 pi .. now how tau- will decay to mu- and tau + will decay to 3 pi ? If you think somehow it is possible defining the decays individually it would be really great if you comment. Thanks a lot.

May I ask what the work is for? Within an experiment (which one) work/analysis?

**Comment by eduardo-rodrigues** [comment]
As I said, what you describe seems to be very common and there is nothing special about it. I don't understand your issues. For the purpose of an example let me write an incomplete solution using B0 -> tau+ tau- since simple. It is trivial to adapt to your real use-case (need to adapt the actual decay modes and complete them, modify branching fractions and decay models):

```
Alias       B0sig           B0
Alias       anti-B0sig      anti-B0
ChargeConj  B0sig           anti-B0sig

Alias         MyFirstTau-     tau-
Alias         MyFirstTau+     tau+
ChargeConj    MyFirstTau+     MyFirstTau-

Alias         MySecondTau-    tau-
Alias         MySecondTau+    tau+
ChargeConj    MySecondTau+    MySecondTau-

Decay B0sig
  1.000    MyFirstTau-    MySecondTau+    PHSP;
Enddecay
CDecay anti-B0sig

Decay MyFirstTau-
  1.0    pi+ pi- pi+ PHSP;
Enddecay
CDecay MyFirstTau+

Decay MySecondTau+
  1.0    mu- ... PHSP;
Enddecay
CDecay MySecondTau-
```

**Comment by psadangi95** [comment]
> As I said, what you describe seems to be very common and there is nothing special about it. I don't understand your issues. For the purpose of an example let me write an incomplete solution using B0 -> tau+ tau- since simple. It is trivial to adapt to your real use-case (need to adapt the actual decay modes and complete them, modify branching fractions and decay models):
> 
> ```
> Alias       B0sig           B0
> Alias       anti-B0sig      anti-B0
> ChargeConj  B0sig           anti-B0sig
> 
> Alias         MyFirstTau-     tau-
> Alias         MyFirstTau+     tau+
> ChargeConj    MyFirstTau+     MyFirstTau-
> 
> Alias         MySecondTau-    tau-
> Alias         MySecondTau+    tau+
> ChargeConj    MySecondTau+    MySecondTau-
> 
> Decay B0sig
>   1.000    MyFirstTau-    MySecondTau+    PHSP;
> Enddecay
> CDecay anti-B0sig
> 
> Decay MyFirstTau-
>   1.0    pi+ pi- pi+ PHSP;
> Enddecay
> CDecay MyFirstTau+
> 
> Decay MySecondTau+
>   1.0    mu- ... PHSP;
> Enddecay
> CDecay MySecondTau-
> ```

Hi @eduardo-rodrigues 

yes i could do it upto now, but what if there are some complex cases like the resonances should be included or excluded in this type of either or decay chain? Is there a way to do such things using decay language ? or will it be taken care separately ? May be i am not aware of those things.

**Comment by eduardo-rodrigues** [comment]
Resonances are all over and just as easy. Please check again the "master" .DEC files in https://github.com/scikit-hep/decaylanguage/tree/master/src/decaylanguage/data for many decay modes of several particles where several resonances appear in the final state. Have you also looked at the EvgGen documentation?

Again, what kind of work/task are you trying to do? Maybe for a specific experiment?

Decay .dec files allow you to define anything. If by "decay language" you mean the classes then there you have the limitation that a single decay chain is possible, as per the examples, meaning you can not define via the classes a particular particle decay to two different final states. This limitation is one of the reasons why the full description is done behind the scenes always as a dict ... But you probably don't want to get to those details.

**Comment by psadangi95** [comment]
> Resonances are all over and just as easy. Please check again the "master" .DEC files in https://github.com/scikit-hep/decaylanguage/tree/master/src/decaylanguage/data for many decay modes of several particles where several resonances appear in the final state. Have you also looked at the EvgGen documentation?
> 
> Again, what kind of work/task are you trying to do? Maybe for a specific experiment?
> 
> Decay .dec files allow you to define anything. If by "decay language" you mean the classes then there you have the limitation that a single decay chain is possible, as per the examples, meaning you can not define via the classes a particular particle decay to two different final states. This limitation is one of the reasons why the full description is done behind the scenes always as a dict ... But you probably don't want to get to those details.

Right now i am trying to learn it to some extent, with drawing the decay chains. Definitely i will apply in the analysis work too.

**Comment by eduardo-rodrigues** [comment]
So far I saw no issue and all was about undestanding decay files, EvtGen, etc. Hence I'm closing. Feel free to reopen if you have follow-ups, or else open more scoped issues.
