### ISSUE TITLE
Numbers in decay models are parsed as parameters

### ISSUE THREAD

**Issue by manuelfs** [scikit-hep/decaylanguage#173]
For decay models with numbers in the name (eg, `HQET2`), the number is parsed as a parameter. For instance, this minimal code
```python
from decaylanguage import DecFileParser
from decaylanguage.dec.dec import get_model_name

s = """Decay B0sig
0.0030  MyD_0*- mu+ nu_mu       PHOTOS  ISGW2;
0.0493  MyD*-   mu+ nu_mu       HQET2 1.207 0.908 1.406 0.853;
0.0493  MyD*-   mu+ nu_mu       HQET 1.207 0.908 1.406 0.853;
Enddecay
"""

dfp = DecFileParser.from_string(s)
dfp.parse()
dms = dfp._find_decay_modes('B0sig')
for dm in dms:
    dm_details = dfp._decay_mode_details(dm, True)

    print('Model name: ', get_model_name(dm))

    for detail in dm_details:
        print(detail)
```
outputs
```
Model name:  ISGW
0.003
['MyD_0*-', 'mu+', 'nu_mu']
PHOTOS ISGW
[2.0]
Model name:  HQET
0.0493
['MyD*-', 'mu+', 'nu_mu']
HQET
[2.0, 1.207, 0.908, 1.406, 0.853]
Model name:  HQET
0.0493
['MyD*-', 'mu+', 'nu_mu']
HQET
[1.207, 0.908, 1.406, 0.853]
```

Indicating that both for `HQET2` and `ISGW2`, the number is taken as a model parameter. I checked this was the behavior with `decaylanguage` tag 0.11.2 and @yipengsun checked that it was still the case in the `master` branch. 

Are we doing something wrong or is this a bug?

**Comment by eduardo-rodrigues** [comment]
Thank you @manuelfs and @yipengsun for reporting. This is indeed a subtle but trivial bug. I have been aware of it in the past, when adding new models to the list of known models, and had fixed things; but I obviously missed these 2. I will provide a fix shortly. The issue has good to do with the way Lark does its efficient parsing.
