### ISSUE TITLE
_repr_svg_() is deprecated from graphviz v0.19

### ISSUE THREAD

**Issue by vvsagar** [scikit-hep/decaylanguage#211]
It looks like `graphviz.Digraph`'s `_repr_svg_()` is replaced by `_repr_mimebundle_(include, exclude)` now: see [changelog](https://graphviz.readthedocs.io/en/stable/changelog.html#version-0-19).

This seems to lead to `AttributeError` when using `DecayChainViewer` in notebooks.

I am still figuring out how to get the rendered image using `_repr_mimebundle_()` instead of just SVG string.

**Comment by vvsagar** [comment]
Okay, using `_repr_image_svg_xml()` seems to do the trick.

**Comment by eduardo-rodrigues** [comment]
Thank you for reporting. We will have to see whether we pin 0.18.* for now or make the code work with both 0.18 and 0.19 ...

Out of curiosity, what work are you using DecayLanguage for?

**Comment by vvsagar** [comment]
Or you could also force >=0.19, right?

I am trying to understand the B-tagging at Belle (II) and using DecayLanguage to study the current MC modeling, to see how well it agrees with PDG, and how it can be further improved. Along the way I made some custom functions like `build_decay_chains_to_inclusive_fsp`, `build_decay_chains_to_specific_fsp` (which identifies all possible intermediate resonances), modified `DecayChainViewer` to show effective BF at fsp level and `DecayChainToTable`.
You can see some of it in [this example notebook](https://github.com/vvsagar/decaylanguage/blob/inclusive-bf-studies/notebooks/ExampleInclusiveBF.ipynb). I was mostly hacking things for my convinence, but if you think any of this would be useful features, I can optimize and make official PRs.

**Comment by eduardo-rodrigues** [comment]
> Or you could also force >=0.19, right?

This would not be a good idea just now since version 0.19 is very new. Users should still have the choice.

> I am trying to understand the B-tagging at Belle (II) and using DecayLanguage to study the current MC modeling, to see how well it agrees with PDG, and how it can be further improved. Along the way I made some custom functions like `build_decay_chains_to_inclusive_fsp`, `build_decay_chains_to_specific_fsp` (which identifies all possible intermediate resonances), modified `DecayChainViewer` to show effective BF at fsp level and `DecayChainToTable`. You can see some of it in [this example notebook](https://github.com/vvsagar/decaylanguage/blob/inclusive-bf-studies/notebooks/ExampleInclusiveBF.ipynb). I was mostly hacking things for my convinence, but if you think any of this would be useful features, I can optimize and make official PRs.

Yes I think some of that work could be integrated into the package. It's certainly been on my to-do list since a while to implement some of the things you have been doing. Feel free to open a dedicated issue so that we discuss what exactly to implement, and how. Advance thanks for your contributions.
