### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by klieret** [scikit-hep/decaylanguage#224]
Let me quickly report that `https://github.com/scikit-hep/decaylanguage/tree/master/decaylanguage/data` from the readme is dead.

**Comment by eduardo-rodrigues** [comment]
Thanks for reporting. It's https://github.com/scikit-hep/decaylanguage/tree/master/src/decaylanguage/data for sure since the code is since a while under src/. But where is the link? I'm not seeing it. Happy if you commit the trivial fix and I then see where you found it :-).

**Comment by klieret** [comment]
Hehe, sorry for being lazy ;)  I opened a PR
