### ISSUE TITLE
How to extract branching fractions?

### ISSUE THREAD

**Issue by acampove** [scikit-hep/decaylanguage#231]
Dear Authors,

Thanks for this project. I am looking at a decay file that looks like:

https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/master/dkfiles/Bu_JpsiX,ee=JpsiInAcc.dec

and in particular the section:

![image](https://user-images.githubusercontent.com/14037062/161561576-30f3f791-ae8d-469b-a050-63c4cd9206ab.png)

Where the numbers are not the absolute fractions, for instance, the B^+\to J/\psi K^+ process has a BF=1e-3

![image](https://user-images.githubusercontent.com/14037062/161561641-166f971e-7bb0-4121-84a3-33cc99662714.png)

Is there a way to retrieve the actual branching fractions with this project? I could not see anything like that in the documentation, although I might have missed it. Ideally I would do something like:

```python
import pdg_reader as pdgr

ifile=pdgr.load_decays(decay_path)
block=ifile.read_block('B+sig')
#Get PDG fractions instead of the ones in the file (relative?)
l_bf = block.get_bf(kind='absolute')
```

Cheers.

**Comment by eduardo-rodrigues** [comment]
Thank you for the interest.

Before anything - I assume you know decay files well and know that the numbers provided as "branching fractions" are only relative to each other within a DECAY statement, meaning dec files contain no information whatsoever on the real and absolute branching fractions. What is that you are trying to do, that needs the absolute BFs?

The easiest may well be to scale all relative BFs in the dec file by the one of the largest BF mode. for visual inspection you can use the method at https://github.com/scikit-hep/decaylanguage/blob/master/src/decaylanguage/dec/dec.py#L692-L722. You could even expand on that and apply on the fly a scaling factor ... As said, depends on what you're trying to achieve.

**Comment by acampove** [comment]
Dear Eduardo,

> Thank you for the interest.
> 
> Before anything - I assume you know decay files well and know that the numbers provided as "branching fractions" are only relative to each other within a DECAY statement, meaning dec files contain no information whatsoever on the real and absolute branching fractions. What is that you are trying to do, that needs the absolute BFs?

Yes, I know that those fractions are only relative. I am trying to use different samples, associated to different decay files, as background components and I need to know their relative importance so that I can use them to constrain or fix the corresponding yields.
> 
> The easiest may well be to scale all relative BFs in the dec file by the one of the largest BF mode. for visual inspection you can use the method at https://github.com/scikit-hep/decaylanguage/blob/master/src/decaylanguage/dec/dec.py#L692-L722. You could even expand on that and apply on the fly a scaling factor ... As said, depends on what you're trying to achieve.

Given that we have multiple decay files `D1`, `D2`, `D3` and each provides a set of decays that contribute to our background:

![CodeCogsEqn (1)](https://user-images.githubusercontent.com/14037062/161687696-74d89be0-efbb-4b0f-bf98-2ab034db8b2c.svg)

where the proportionality constant is a parameter in the fit and the epsilons are the efficiency provided by the user, which is analysis dependent. However the `F` is:

![CodeCogsEqn (2)](https://user-images.githubusercontent.com/14037062/161688272-c29601d0-c69f-4601-af6b-d2d19c73e862.svg)

the sum of the decay branching fractions (which as you said can be calculated by knowing just one of the numbers) multiplied by the mother particles production cross section. In my case, one of my decays starts from a B+ and the other from a B_d so I can just assume the same sigma. In any case, I was thinking of doing in my code something like:

```python

import some_module as md

obj    = md.load(dec_file_path)
bf_bp = obj.get_total_branching_fraction('B-sig')
```
and the tool would just figure out how to get this number. What I did not know was what tool can provide those branching fractions, given the decay file so that I do not do it by hand. If this is not available through `decaylanguage` I can write it as part of my code and maybe do a pull request eventually to integrate it in `decaylanguage`.

In order to do that, it would be good to know where the whole PDG data is stored so that I can read it with my code. Once I asked the PDG about an API for interacting with their data, but they did not have anything like that available and the only way to read their numbers was to do it though their web interface.

Cheers.

**Comment by eduardo-rodrigues** [comment]
Up to you but I would not bind too much the decay files to the background cocktail because you need to involve selection efficiencies and hadronisation probabilities when calculating relative contributions. In the end all that the decay files gives you are the relative decay probabilities for a given MC sample and a given mother particle.

This package contains decay files. Most are under tests/data (for testing) but the main ones are copies of the "master" DECAY.DEC from LHCb and Belle II, see https://github.com/scikit-hep/decaylanguage/tree/master/src/decaylanguage/data. They are just about the latest versions. Most of the time the user inputs the decay file(s) they need, as you can imagine.

The PDG decay data is not stored in this package. That's in the PDG site and not easily accessible, as you mention. It would anyway be an overkill for you to parse a gigantic JSON file to simply store a handful of absolute BFs, I would say. Up to you.

I still think my suggestion above of an enhancement to 1 or 2 functions would be the easiest. Having the package enhanced always helps others, of course. We very much welcome community contributions!

**Comment by eduardo-rodrigues** [comment]
BTW, to be more comprehensive: I've also been in touch with the PDG several times and would love to be able to easily query their decay data to provide the kind of thing you are trying to do in a straightforward way, and more. But the provision of all that PDG decay data via an API does not depend on me ;-).

**Comment by acampove** [comment]
> Up to you but I would not bind too much the decay files to the background cocktail because you need to involve selection efficiencies and hadronisation probabilities when calculating relative contributions. In the end all that the decay files gives you are the relative decay probabilities for a given MC sample and a given mother particle.

Yes, we are planning to add the selection efficiencies (epsilons in the stuff above). However the hadronisation probabilities are the same or very similar between all our decays given that they all come from either B+ or Bd. 

> 
> This package contains decay files. Most are under tests/data (for testing) but the main ones are copies of the "master" DECAY.DEC from LHCb and Belle II, see https://github.com/scikit-hep/decaylanguage/tree/master/src/decaylanguage/data. They are just about the latest versions. Most of the time the user inputs the decay file(s) they need, as you can imagine.
> 
> The PDG decay data is not stored in this package. That's in the PDG site and not easily accessible, as you mention. It would anyway be an overkill for you to parse a gigantic JSON file to simply store a handful of absolute BFs, I would say. Up to you.
> 
> I still think my suggestion above of an enhancement to 1 or 2 functions would be the easiest. Having the package enhanced always helps others, of course. We very much welcome community contributions!

Ok, thanks for your feedback. I will try to figure out a convenient (safe, simple, mistake proof) way of doing this.

**Comment by eduardo-rodrigues** [comment]
OK. By all means do get in touch if interested in contributing anything to this package, where relevant. Thanks.

**Comment by eduardo-rodrigues** [comment]
Hi @acampove, just to say that I went ahead and implemented the kind of BF scaling you were looking for, though that's only done now in the printing, not changing any values stored in memory, see PR https://github.com/scikit-hep/decaylanguage/pull/233. With a bit more work in some of the class helper functions you would easily achieve what you need.

**Comment by acampove** [comment]
Hi @eduardo-rodrigues 

Thanks for your help. From:

https://github.com/scikit-hep/decaylanguage/commit/8c6af22f947f28454a4f5e9f0bd2f524be4afccc#diff-eee2bf4814d95a6e3e6aeac054225e82f4b6b0783d532f93f0b2d013e35ae0faR802

I see that there is an extra flag, `scale` and an unmodified behavior for `normalize`:

`normalize==true`: Will make sure that the sum of BF is 1, although I remember this is supposed to be already true. So we should never see any difference. As you seem to have found out:

https://github.com/scikit-hep/decaylanguage/blob/master/tests/dec/test_dec.py#L373

In case that the sum is not 1 by default, that might mean that some non-negligible decays are not included. In this case I do not think we should be normalizing to 1 and probably we should not even be using the sample, given that it's not really representative of the Physics we would see.

`scale=number`: This is not really a scale, if I use `0.5` I see:

![image](https://user-images.githubusercontent.com/14037062/162680026-026ebdc8-d9ed-476c-848c-074f21a96466.png)

meaning, this is going to replace the largest BF in the section with `scale` and recalculate everything with respect to this number. However, we would still need to find out what the largest BF is by parsing the decay file and then, extract the list of BFs as the list of the first elements in:

https://github.com/scikit-hep/decaylanguage/commit/8c6af22f947f28454a4f5e9f0bd2f524be4afccc#diff-eee2bf4814d95a6e3e6aeac054225e82f4b6b0783d532f93f0b2d013e35ae0faR799

As you said before, parsing the BF from the LHCB decay file would be pretty challenging given that it's a huge file:

1. Is there software out there to parse DEC files? I assume `decaylanguage` is the only software.
2. Why use DEC files, I am assuming there must be much better formats out there to store large amounts of data.

In the long term the way to go here is probably:

1. Parse the large DEC file in an efficient way using a DEC reader class.
2. Plug this class into decaylanguage and update the code so that the scale arg is replaced with the BF. 
3. Test the scaling with different BF, not just the largest decay, to make sure that they all give compatible lists of BF.

However, I do not know if I can afford doing all this, given that this particular task is just a small part of our analysis and our time budget might not allow for it. In any case, I will see what I can do and if something good comes out of it, I might do a pull request.

Cheers.

PS: I used:

```python
def test():
    pobj = DecFileParser('bpXcHs.dec')
    pobj.parse()

    old_stdout = sys.stdout

    tmp_stdout = io.StringIO()
    sys.stdout = tmp_stdout
    pobj.print_decay_modes("B-sig")
    out_1 = tmp_stdout.getvalue()

    tmp_stdout = io.StringIO()
    sys.stdout = tmp_stdout
    pobj.print_decay_modes("B-sig", normalize=True)
    out_2 = tmp_stdout.getvalue()

    tmp_stdout = io.StringIO()
    sys.stdout = tmp_stdout
    pobj.print_decay_modes("B-sig", scale=0.5)
    out_3 = tmp_stdout.getvalue()

    sys.stdout = old_stdout

    del old_stdout, tmp_stdout

    print(out_1)
    print(out_2)
    print(out_3)
#-------------------------------------------------------------
test()
```
for my tests, with:

https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/master/dkfiles/Bu_JpsiX,ee=JpsiInAcc.dec

**Comment by eduardo-rodrigues** [comment]
> Hi @eduardo-rodrigues
> 
> Thanks for your help. From:
> 
> [8c6af22#diff-eee2bf4814d95a6e3e6aeac054225e82f4b6b0783d532f93f0b2d013e35ae0faR802](https://github.com/scikit-hep/decaylanguage/commit/8c6af22f947f28454a4f5e9f0bd2f524be4afccc#diff-eee2bf4814d95a6e3e6aeac054225e82f4b6b0783d532f93f0b2d013e35ae0faR802)
> 
> I see that there is an extra flag, `scale` and an unmodified behavior for `normalize`:

I actually changed the default to `normalize = False` for a WYSIWYG experience, which is what one would expect by default - meaning you get printed exactly what is parsed and in the dec file.

> `normalize==true`: Will make sure that the sum of BF is 1, although I remember this is supposed to be already true. So we should never see any difference. As you seem to have found out:

That's indeed true most of the time. But I have come across dec files where the sum is not 1.

> https://github.com/scikit-hep/decaylanguage/blob/master/tests/dec/test_dec.py#L373
> 
> In case that the sum is not 1 by default, that might mean that some non-negligible decays are not included.

Not really since dec files anyway typically focus on a single decay chain or a small set of them. I might write (not ideal, just for the sake of example)

```
Decay B0
1 pi+ pi-    PHSP;
1 pi0 pi0    PHSP;
Enddecay
```

because I happen to want equal mixtures of the 2 modes for some study, but it does not otherwise have any physical meaning.

> In this case I do not think we should be normalizing to 1 and probably we should not even be using the sample, given that it's not really representative of the Physics we would see.

See my comment just above - special studies may mean "unphysical samples" to emphasise some component, for example.

> `scale=number`: This is not really a scale, if I use `0.5` I see:
> 
> ![image](https://user-images.githubusercontent.com/14037062/162680026-026ebdc8-d9ed-476c-848c-074f21a96466.png)
> 
> meaning, this is going to replace the largest BF in the section with `scale` and recalculate everything with respect to this number.

That's right. Would you prefer `scale_largest_to` or similar? In any case the docstring is very clear on the meaning IMHO.

However, we would still need to find out what the largest BF is by parsing the decay file and then, extract the list of BFs as the list of the first elements in:
> 
> [8c6af22#diff-eee2bf4814d95a6e3e6aeac054225e82f4b6b0783d532f93f0b2d013e35ae0faR799](https://github.com/scikit-hep/decaylanguage/commit/8c6af22f947f28454a4f5e9f0bd2f524be4afccc#diff-eee2bf4814d95a6e3e6aeac054225e82f4b6b0783d532f93f0b2d013e35ae0faR799)

Not really. You can simply print with no scale if you want to see what is defined. But, as said already, the "BF" in a dec file is hardly ever an actual measured BF (approximate) except for what is stored in the master files DECAY.DEC. Keep this in mind.

> As you said before, parsing the BF from the LHCB decay file would be pretty challenging given that it's a huge file:

Why do you say that? DecayLanguage does that in approximately 2 seconds (the 11k lines).

> 1. Is there software out there to parse DEC files? I assume `decaylanguage` is the only software.

The C++ EvtGen package, of course, which is the original user of dec files. I'm not aware of other Python packages, though. And this package provides far more user-friendly tools for the parsing IMHO. This being said, if you are lacking functionality, then please get in touch and suggest and/or contribute.

> 2. Why use DEC files, I am assuming there must be much better formats out there to store large amounts of data.

That's a very different discussion. I guess people went for dec files because you can trivially read them by eye. In the end they are not that large files, hence no need to go fancy and readability is important.

> In the long term the way to go here is probably:
> 
> 1. Parse the large DEC file in an efficient way using a DEC reader class.
> 2. Plug this class into decaylanguage and update the code so that the scale arg is replaced with the BF.
> 3. Test the scaling with different BF, not just the largest decay, to make sure that they all give compatible lists of BF.

This is all doable already now, and efficiently. I do not understand your comment here. The printouts never change the stored contents for one,and also all printouts, normalised or scaled always provide relative BFs that keep to the original related ones on the files. This is all correct.

> However, I do not know if I can afford doing all this, given that this particular task is just a small part of our analysis and our time budget might not allow for it. In any case, I will see what I can do and if something good comes out of it, I might do a pull request.
> 
> Cheers.
> 
> PS: I used:
> 
> ```python
> def test():
>     pobj = DecFileParser('bpXcHs.dec')
>     pobj.parse()
> 
>     old_stdout = sys.stdout
> 
>     tmp_stdout = io.StringIO()
>     sys.stdout = tmp_stdout
>     pobj.print_decay_modes("B-sig")
>     out_1 = tmp_stdout.getvalue()
> 
>     tmp_stdout = io.StringIO()
>     sys.stdout = tmp_stdout
>     pobj.print_decay_modes("B-sig", normalize=True)
>     out_2 = tmp_stdout.getvalue()
> 
>     tmp_stdout = io.StringIO()
>     sys.stdout = tmp_stdout
>     pobj.print_decay_modes("B-sig", scale=0.5)
>     out_3 = tmp_stdout.getvalue()
> 
>     sys.stdout = old_stdout
> 
>     del old_stdout, tmp_stdout
> 
>     print(out_1)
>     print(out_2)
>     print(out_3)
> #-------------------------------------------------------------
> test()
> ```
> 
> for my tests, with:
> 
> https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/master/dkfiles/Bu_JpsiX,ee=JpsiInAcc.dec
