### ISSUE TITLE
General API for decay chain representations

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/decaylanguage#27]
There should be a fairly simple (and documented) way to add a generic decay, so other libraries (like pyhepmc3) can easily use DecayLanguage to build a decay plot. Sharing a bit of code between parts (dec, decay) would be nice too if possible. Also, DecayLanguage's requirements could probably be trimmed (Pandas was mostly for Particle, I expect).

**Comment by eduardo-rodrigues** [comment]
For reference, work has started on this, see PRs https://github.com/scikit-hep/decaylanguage/pull/42 and https://github.com/scikit-hep/decaylanguage/pull/43.

**Comment by eduardo-rodrigues** [comment]
Said in other words, this is WIP to create a sort of unified language for the description of particle decay chains, with visualisation tools.

CC @mattbellis given his interest and previous work - I'll get back to this very soon. You are welcome to follow and comment as PRs come in ...

**Comment by eduardo-rodrigues** [comment]
A serious milestone has been achieve with several PRs and in particular https://github.com/scikit-hep/decaylanguage/pull/72. Now we have a version 0 for the representation of decay chains. I will need feedback from users, and will leave this task open for a bit longer.

**Comment by eduardo-rodrigues** [comment]
I am closing the task at this point given that the classes to represent decay chains have been around for a year.
