### ISSUE TITLE
Functionality to create multiple decay descriptors from a dict when particles have multiple decay modes

### ISSUE THREAD

**Issue by admorris** [scikit-hep/decaylanguage#332]
At the moment it is possible to create a `DecayChain` object from the output of `DecFileParser.build_decay_chains()` only if every particle has only one decay mode defined (enforced by a line that does `assert len(decay_chain_dict.keys()) == 1`).

For the purpose of making a tool that searches DecFiles by decay, I need some functionality that extracts all combinations of decaying particles (i.e. multiple `DecayChain` objects when a particle has multiple decay modes)

**Comment by admorris** [comment]
Yes, that's what I'd like. I was thinking of the word "flattening" but this is used already in another context, so how about "expanding" the decay dicts to a list of unique decay chains.

I have written some similar logic already for the NTuple Wizard [decays.py#L509-579](https://gitlab.cern.ch/lhcb-dpa/wp6-analysis-preservation-and-open-data/lhcb-ntuple-wizard/-/blob/d7bba0a2a6024f046465974ecd39c437e29db42b/src/lhcb_ntuple_wizard/decays.py#L509-579) where it traverses down to the bottom of the tree (the final state) and works its way back up, collecting all combinations that arise from multiple decay modes (and PID substitutions, although that's not relevant here).

**Comment by admorris** [comment]
I mean, they don't have to be `DecayChain` objects since e.g. I'm unsure if it can handle e.g. $B_s \to (\phi K^+ K^-) (\phi \pi^+ \pi^- \pi^0)$ without giving each $\phi$ a unique name. I'd be happy with just strings (decay descriptors) as the output.

**Comment by eduardo-rodrigues** [comment]
Yes "expanding" sounds good to me, and it is easiest in a first implementation to only provide the output as a string (or a DaughtersDict on which you call to_string, if you prefer) .

Indeed there are some limitations and right now your decay Bs -> phi phi with 2 different phi decays would need to have the phi's aliased to different names. This is not too crazy if one things that the decays *are* different, but it is for sure a limitation in certain contexts.

Let's sort in the immediate future your use-case. I guess you will need a release as soon as this is done. Just let me know.

Thanks again,
