### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by jonas-eschle** [scikit-hep/decaylanguage#349]
Can we publish a new version? Python 3.8 currently fails because `importlib_resources` upgraded to v6 and that now breaks decaylanguage without the fix https://github.com/scikit-hep/decaylanguage/pull/346/files#diff-36a3d156625f582e1c074e988e887991da3020422232def6072268303bfa2542L17

**Comment by eduardo-rodrigues** [comment]
Hey there. We sure can. I'm working on some enhancements and simplifications but that can wait.

You mean a release from HEAD? Now is late but I will do it tomorrow?

BTW, where did you see the need? In preparing the new tag of phasespace, I guess?

**Comment by jonas-eschle** [comment]
Golden, thanks a lot! Yes, exactly, phasespace just got a new version and the 3.8 CI was failing
