### ISSUE TITLE
An extra '2' in one line of LHCB dec file?

### ISSUE THREAD

**Issue by ch2ohch2oh** [scikit-hep/decaylanguage#90]
https://github.com/scikit-hep/decaylanguage/blob/9a02b51fe2db7abf001c8a81d690a1f9e6d14857/decaylanguage/data/DECAY_LHCB.DEC#L291

There seems to be an extra digit 2 in one line of the dec file. It should work with current version of the `decfile.lark` but I believe it should not be there. I was playing around with the `decfile.lark` to incorporate decay line like this
```
Decay xxx
0.5 SOME_MODEL 1 2 3
      4 5 6; # some comments
Dnddecay
```
That is how I found this extra 2.

**Comment by eduardo-rodrigues** [comment]
First of all, many thanks for using the package!

Yes, this seems to be a buglet in the LHCb master file and I will pass the information on. I will check what information gets returned after parsing, since the parsing does end OK.

**Comment by ch2ohch2oh** [comment]
From my understanding, the program parsed this line fine because in your `decfile.lark`, both `;` and `#` are treated as keywords for comments.

**Comment by eduardo-rodrigues** [comment]
Yep, indeed. I will try and review your related PR today, to close this.

**Comment by eduardo-rodrigues** [comment]
Closed via https://github.com/scikit-hep/decaylanguage/pull/91.

**Comment by henryiii** [comment]
Have you verified that this has been changed in the official file? This file is only an example, the goal is to read the real file, not a modified copy.

**Comment by eduardo-rodrigues** [comment]
Did you not see my last comment in https://github.com/scikit-hep/decaylanguage/pull/91? Does it not directly address your worry? Unless I misunderstood. The removal of a comment letter is not a reason to block the PR, I reckon.

**Comment by henryiii** [comment]
Okay, as long as the problem gets fixed, I'm fine with it being strict. It would be nice if we can get this used officially, yes. I'd like users of Decfiles to also be stricter, though.

**Comment by eduardo-rodrigues** [comment]
Well, that's the idea, of course.

As for stricter rules, which make DecFiles better, that would be great. But keep in mind that the "showstopper" is EvtGen, which is the consumer of DecFiles. Clearly EvtGen is sloppy in various places. A comprehensive fix would have to be propagated there too. Fortunately the LHCb coordinator I talked to is one of the EvtGen maintainers ;-).
