### ISSUE TITLE
pydot required but not installed

### ISSUE THREAD

**Issue by daritter** [scikit-hep/decaylanguage#99]
I just installed decaylanguage via `pip3 install decaylanguage` and then tried to

```
from decaylanguage import DecFileParser
```
but this resulted in

```
Traceback (most recent call last):
  File "/home/ritter/belle2/software/decfiles/tests/parse_decfiles.py", line 2, in <module>
    from decaylanguage import DecFileParser
  File "/home/ritter/belle2/externals/v01-09-00/Linux_x86_64/common/lib/python3.6/site-packages/decaylanguage/__init__.py", line 14, in <module>
    from .decay import DecayChainViewer
  File "/home/ritter/belle2/externals/v01-09-00/Linux_x86_64/common/lib/python3.6/site-packages/decaylanguage/decay/__init__.py", line 4, in <module>
    from .viewer import DecayChainViewer
  File "/home/ritter/belle2/externals/v01-09-00/Linux_x86_64/common/lib/python3.6/site-packages/decaylanguage/decay/viewer.py", line 21, in <module>
    raise ImportError("You need pydot for this submodule. Please install pydot with for example 'pip install pydot'\n")
ImportError: You need pydot for this submodule. Please install pydot with for example 'pip install pydot'
```

It seems that pydot is not optional but apparently not in the requirements. Can we make it an optional dependency? Or add it to the requirements?

**Comment by henryiii** [comment]
Oops, yes, one of the two. Probably an optional requirement; we need to fix the error when not using the viewer, and probably add a better `[vis]` or `[all]` or something like that optional requirement in the pip install.

**Comment by eduardo-rodrigues** [comment]
The message is clear - "You need pydot for this submodule. Please install pydot with for example 'pip install pydot'" ;-). But agreed that we can expand the set up. I have no strong opinion. Right now you get `pydot` with [notebook], for example, see `https://github.com/scikit-hep/decaylanguage/blob/master/setup.py`.

**Comment by eduardo-rodrigues** [comment]
BTW, before you ask - I know that we need to make a new release to patch the major release 0.10.0 of `Particle` … It's on the to-do list.

**Comment by henryiii** [comment]
`from decaylanguage import DecFileParser` should not require pydot, though.

**Comment by eduardo-rodrigues** [comment]
Yeah, that's because the class is available from the top level, see `https://github.com/scikit-hep/decaylanguage/blob/master/decaylanguage/__init__.py`.

**Comment by daritter** [comment]
I'm also fine with having pydot and yes, the message is clear, but `pip install` should hopefully give me a working package so if we just include it in the requirements so it gets pulled in automatically I would be fully happy :D

**Comment by henryiii** [comment]
Warning on the wrapped import in `decaylanguage/decay/viewer.py`: it hides the import problem (for example, if a pydot dependency is unimportable, a user can't tell). It's really hard to wrap these correctly, especially in a Python 2+3 codebase. See what I did in boost-histogram: 

https://github.com/scikit-hep/boost-histogram/blob/c20cdf4afc97b38da420d79118ac85a991bed762/src/boost_histogram/__init__.py#L10-L30

**Comment by eduardo-rodrigues** [comment]
@henryiii, what's on opinion on simply adding `pydot` to the requirements? It's not that heavy a heavy dependency and I can imagine that almost anyone parsing decay files will also do some plots.

I noticed that `pydot` is not being worked on since 1.5 years and we will need to move to `graphviz`, but that's a separate issue, for a separate thread.

**Comment by henryiii** [comment]
From the graphviz download page:

> To render the generated DOT source code, you also need to install Graphviz (download page).

I think visualization should remain separate from the core requirements. @daritter's usage, for example, does not need visualization.

However, it looks like we could possibly require graphviz, then only render the output if the compiled program is installed (at that's a heavy, non-Python dependency). Something to decide after we move to graphviz, I expect.

**Comment by eduardo-rodrigues** [comment]
OK, then we should support an extra as you mention above. Right now `pydot` can be pip installed with the `notebook` extra, actually.

@daritter, happy if we create a `viz` or `all` extra?

**Comment by henryiii** [comment]
`pydot` also requires you install graphviz the compiled library using your system package manager (or conda). Both libraries are easy pip installs, but neither library actually works until you set up an external install (the same one).

**Comment by eduardo-rodrigues** [comment]
Once we converge on this here we can quickly prepare a patch release.

**Comment by daritter** [comment]
> `pydot` also requires you install graphviz the compiled library using your system package manager (or conda). Both libraries are easy pip installs, but neither library actually works until you set up an external install (the same one).

so I vote for just adding the dependency. I was a bit worried that it would bring the whole of graphviz but as it is I can perfectly live with adding another tiny package and keep the code simpler

**Comment by eduardo-rodrigues** [comment]
Thanks. Let's give Henry an opportunity to comment and we take action - he will be online in the afternoon.

**Comment by eduardo-rodrigues** [comment]
@henryiii, happy for `pydot` to be a dependency? We should make a new release as soon as this is settled. I can take care of this.

**Comment by henryiii** [comment]
New version released. Now powered by GHA, and updated the scikit-hep dev pages just a bit.
